name: FastAPI CI/CD with MongoDB Atlas

on:
  push:
    branches:
      - ci-2
  workflow_dispatch:
  schedule:
    # 매일 12시에 실행
    - cron: '0 12 * * *'

jobs:
  test:
    runs-on: windows-latest

    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Python 설치
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # 3. 의존성 설치
      - name: Install dependencies
        run: |
          python -m venv venv
          .\venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. FastAPI 서버 실행 (백그라운드)
      - name: Start FastAPI server
        run: |
          .\venv\Scripts\activate
          uvicorn app.main:app --host 0.0.0.0 --port 8080 --log-level debug > server.log 2>&1 &
          Start-Sleep -Seconds 10  # 서버가 충분히 초기화될 수 있도록 대기 시간 늘리기
          Get-Content server.log

      # 5. MongoDB 업데이트 요청
      - name: Update MongoDB Database
        run: |
          try {
            $response = Invoke-WebRequest -Uri "http://127.0.0.1:8080/mongo/restday-update-db" -Method GET -TimeoutSec 5
            Write-Host "API Response:"
            Write-Host $response.Content
          }
          catch {
            Write-Error "API 호출 실패: $_"
            exit 1
          }

      # 6. 서버 종료 (FastAPI 서버 종료)
      - name: Shutdown FastAPI server
        run: |
          Write-Host "Shutting down FastAPI server..."
          Stop-Process -Name "uvicorn" -Force

