name: FastAPI CI

on:
  push:
    branches:
      - ci-1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Start FastAPI server in the background
        run: |
          source .venv/bin/activate
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8080 &

      - name: Wait for server to start
        run: sleep 5  # Wait for 5 seconds to ensure the server starts

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest
