name: FastAPI CI/CD with MongoDB Atlas

on:
  push:
    branches:
      - ci-1
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest  # Windows 환경에서 실행

    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Python 설치
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # 캐시 정리
      - name: Clear Python cache
        run: python -m pip cache purge

      # 3. 의존성 패키지 설치
      - name: Install dependencies
        run: |
          python -m venv venv
          .\venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # utf-8 인코딩    
      - name: Set UTF-8 Encoding
        run: |
          [System.Console]::OutputEncoding = [System.Text.Encoding]::UTF8


      # 4. 환경 변수 설정
      - name: Set environment variables
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          Write-Host "Environment variables configured."

      # 5. FastAPI 서버 실행 (백그라운드)
      - name: Start FastAPI server
        run: |
          .\venv\Scripts\activate
          uvicorn app.main:app --host 0.0.0.0 --port 5835 --log-level debug > server.log 2>&1 &
          Start-Sleep -Seconds 5
          Get-Content server.log

      # 서버 동작 테스트 유효성 검사
      - name: Check if FastAPI server is running
        run: |
          try {
            $response = Invoke-WebRequest -Uri "http://127.0.0.1:5835" -Method GET -TimeoutSec 5
            Write-Host "Server is running. Response:"
            Write-Host $response.Content
          }
          catch {
            Write-Error "Server check failed: $_"
            exit 1
          }

      # 7. /mongo/restday-update-db 호출 (Invoke-WebRequest 사용)
      - name: Call MongoDB Update API using Invoke-WebRequest
        run: |
          try {
            $response = Invoke-WebRequest -Uri "http://127.0.0.1:5835/mongo/restday-update-db" -Method GET
            Write-Host "API Response:"
            Write-Host $response.Content
          }
          catch {
            Write-Error "API 호출 실패: $_"
            exit 1
          }
