name: FastAPI CI/CD with MongoDB Atlas

on:
  push:
    branches:
      - ci-1
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest  # Windows 환경에서 실행

    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Python 설치
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # 3. 의존성 패키지 설치
      - name: Install dependencies
        run: |
          python -m venv .venv
          .\.venv\Scripts\activate
          pip install -r requirements.txt

      # 4. 환경 변수 설정
      - name: Set environment variables
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          Write-Host "Environment variables configured."

      # 5. FastAPI 서버 실행 (백그라운드)
      - name: Start FastAPI server
        run: |
          .\.venv\Scripts\activate
          Start-Process "uvicorn" -ArgumentList "app.main:app --host 0.0.0.0 --port 5835" -NoNewWindow
          Write-Host "FastAPI server started on port 5835"

      # 6. 서버 시작 대기
      - name: Wait for server to start
        run: |
          $retries = 10
          $success = $false
          for ($i=0; $i -lt $retries; $i++) {
            try {
              $response = Invoke-WebRequest -Uri "http://127.0.0.1:5835" -Method GET
              if ($response.StatusCode -eq 200) {
                $success = $true
                break
              }
            }
            catch {
              Start-Sleep -Seconds 3
            }
          }
          if (-not $success) {
            Write-Host "Server did not start in time"
            exit 1
          }

      # 7. /mongo/restday-update-db 호출 (curl 사용)
      - name: Call MongoDB Update API using curl
        run: |
          curl.exe -v -X GET "http://127.0.0.1:5835/mongo/restday-update-db"
          Write-Host "finished work"

      # 8. /mongo/restday-update-db 호출 (Invoke-WebRequest 사용)
      - name: Call MongoDB Update API using Invoke-WebRequest
        run: |
          Invoke-WebRequest -Uri "http://127.0.0.1:5835/mongo/restday-update-db" -Method GET
          Write-Host "finished work"
