name: FastAPI CI/CD with MongoDB Atlas

on:
  push:
    branches:
      - ci-1
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Python 설치
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # 3. 의존성 패키지 설치
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      # 4. 환경 변수 설정
      - name: Set environment variables
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: echo "Environment variables configured."

      # 5. FastAPI 서버 실행 (백그라운드)
      - name: Start FastAPI server
        run: |
          source .venv/bin/activate
          uvicorn app.main:app --host 0.0.0.0 --port 5835 &
          echo "FastAPI server started on port 5835"

      # 6. 서버 시작 대기 (시간을 좀 더 길게 설정하거나 체크 후 요청)
      - name: Wait for server to start
        run: |
          for i in {1..10}; do
            curl -s http://127.0.0.1:5835 > /dev/null && break || sleep 3
          done

      # 7. /mongo/restday-update-db 호출
      - name: Call MongoDB Update API
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          curl -v -X GET "http://127.0.0.1:5835/mongo/restday-update-db"
          echo "finished work"
