name: FastAPI CI

on:
  push:
    branches:
      - ci-1
  workflow_dispatch:
  # 워크플로우는 수동 실행
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 파이썬 설치
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: package 설치
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: 환경 변수 설정
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          echo "환경 변수 설정 완료"

      - name: Fast API 백그라운드 실행
        run: |
          source .venv/bin/activate 
          nohup uvicorn app.main:app --host 0.0.0.0 --port 5835 & 
          
      - name: 서버 실행 5초 기다리기
        run: sleep 5  # 서버가 시작될 때까지 기다리는 작업

      - name: API URL 생성
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          source .venv/bin/activate
          python -c "from app.lib.get_API_URL import get_API_URL;"

